  ALTER TABLE MyModel ADD COLUMN powerRange_max INTEGER;
  ALTER TABLE MyModel ADD COLUMN powerRange_min INTEGER;
   ALTER TABLE MyModel ADD COLUMN jouleRange_max INTEGER;
  ALTER TABLE MyModel ADD COLUMN jouleRange_min INTEGER;
  ALTER TABLE MyModel ADD COLUMN showName TEXT;
